import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react"
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Post from '../components/Post'
import Navbar from '../components/Navbar';
import { useState, useCallback, useEffect } from 'react';

 
import { Container, Row, Col } from "reactstrap";

const useMediaQuery = (width) => {
  const [targetReached, setTargetReached] = useState(false);

  const updateTarget = useCallback((e) => {
    if (e.matches) {
      setTargetReached(true);
    } else {
      setTargetReached(false);
    }
  }, []);

  useEffect(() => {
    const media = window.matchMedia(`(max-width: ${width}px)`);
    media.addListener(updateTarget);

    // Check on mount (callback is not called until a change occurs)
    if (media.matches) {
      setTargetReached(true);
    }

    return () => media.removeListener(updateTarget);
  }, []);

  return targetReached;
};

const Header = () => {
  const isBreakpoint = useMediaQuery(768)
   
  return (
      isBreakpoint ? (
       <div className={styles.banner}> 
          <Image
          src="/images/header_mobile.jpg"
          alt='Header Image'
          layout = "responsive"
          width={825}
          height={825}
          
          />
       </div>
     ) 
     : 
     (
      <div className={styles.banner}>
        <Image
        src="/images/header2.jpg"
        alt='Header Image'
        layout = "responsive"
        width={3360}
        height={840}
        priority={true}
        />
      </div>
    )
)}




export default function Home({posts}) {
  //console.log(posts);
  return (
    <div >
      <Head>
        <title>MRH Sticker Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      
      <main>
        <header >
          <Header />
        </header>

        <div className='padding'>
        <style jsx>{`
          .padding {
            padding: 30px;
          }
        `}
          
        </style>
        <div className={styles.container}> 
          <Container className={styles.title1} >
            SHOP BY FANDOM
          </Container>
          <Row>
            <Col className={styles.headerImage} xs="12" lg="4">
              <div className={styles.imageShadow}>
                <Image className={styles.image}
                    src="/images/mandol.jpeg"
                    alt='Header Image'
                    layout = "responsive"
                    width={500}
                    height={500}
                  />
              </div>
              STAR WARS
            </Col>
            <Col className={styles.headerImage} xs="12" lg="4">
              <div className={styles.imageShadow}>
                <Image className={styles.image}
                    src="/images/olaf.jpeg"
                    alt='Header Image'
                    layout = "responsive"
                    width={500}
                    height={500}
                  />
              </div>
              <a>
                DISNEY
              </a>
              
            </Col>
            <Col className={styles.headerImage} xs="12" lg="4">
              <div className={styles.imageShadow}>
                <Image className={styles.image}
                    src="/images/turtles.jpg"
                    alt='Header Image'
                    layout = "responsive"
                    width={500}
                    height={500}
                />
              </div>
              
              OTHER
            </Col>
          </Row>
        </div>

        </div>
        
        

        <Container className={styles.title} id="contact"  >
          SHOP ALL STICKERS
        </Container>
    
       
        <Row className='row'>
          <div className='row'>
          {posts.map((post, index) => (
                  <Post post={post}/>
                ))}
          </div>
          
        </Row>
     
       
       
        
          
         
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export async function getStaticProps(){

  // gets files from posts directory
  const files = fs.readdirSync(path.join('posts'))

  // get slug and frontmatter from posts
  const posts = files.map(filename => {
    //create slug 
    const slug = filename.replace('.md', '')

    //get frontmatter
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    // using the matter function, rename data to frontmatter and populate it with the 
    // data from the markdown file
    const {data:frontmatter} = matter(markdownWithMeta)

    return {
      slug,
      frontmatter
    }
  })

  // return the posts from the file map to the home page
  return {
    props: {
      posts,
    }
  }
}
