import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react"
import Navbar from '../components/Navbar';
import { useState, useCallback, useEffect } from 'react';

import { getAllPostIds, getPostData } from '../lib/posts'

import { Container, Row, Col } from "reactstrap";

const useMediaQuery = (width) => {
  const [targetReached, setTargetReached] = useState(false);

  const updateTarget = useCallback((e) => {
    if (e.matches) {
      setTargetReached(true);
    } else {
      setTargetReached(false);
    }
  }, []);

  useEffect(() => {
    const media = window.matchMedia(`(max-width: ${width}px)`);
    media.addListener(updateTarget);

    // Check on mount (callback is not called until a change occurs)
    if (media.matches) {
      setTargetReached(true);
    }

    return () => media.removeListener(updateTarget);
  }, []);

  return targetReached;
};

const Header = () => {
  const isBreakpoint = useMediaQuery(768)
  console.log("Here is postdata: " + getAllPostIds.length);
  console.log(params.id);
  return (
      isBreakpoint ? (
       <div className={styles.banner}> 
          <Image
          src="/images/header_mobile.jpg"
          alt='Header Image'
          layout = "responsive"
          width={825}
          height={825}
          
          />
       </div>
     ) 
     : 
     (
      <div className={styles.banner}>
        <Image
        src="/images/header2.jpg"
        alt='Header Image'
        layout = "responsive"
        width={3360}
        height={840}
        priority={true}
        />
      </div>
    )
)}




export default function Home() {
  return (
    <div >
      <Head>
        <title>MRH Sticker Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      
      <main>
        <header >
          <Navbar />
          <Header />
        </header>

        <div className='padding'>
        <style jsx>{`
          .padding {
            padding: 30px;
          }
        `}
          
        </style>
        <div className={styles.container}> 
          <Container className={styles.title1} >
            SHOP BY FANDOM
          </Container>
          <Row>
            <Col className={styles.headerImage} xs="12" lg="4">
              <Image 
                  src="/images/mandol.jpeg"
                  alt='Header Image'
                  layout = "responsive"
                  width={500}
                  height={500}
                />
              STAR WARS
            </Col>
            <Col className={styles.headerImage} xs="12" lg="4">
              <Image 
                  src="/images/olaf.jpeg"
                  alt='Header Image'
                  layout = "responsive"
                  width={500}
                  height={500}
                />
              DISNEY
            </Col>
            <Col className={styles.headerImage} xs="12" lg="4">
              <Image 
                  src="/images/turtles.jpg"
                  alt='Header Image'
                  layout = "responsive"
                  width={500}
                  height={500}
              />
              OTHER
            </Col>
          </Row>
        </div>

        </div>
        
        

        <Container className={styles.title} id="contact"  >
          SHOP ALL STICKERS
        </Container>

      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
